import = ["~/.config/alacritty/tokyo-night.toml"]

[window]
opacity = 0.7

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
