general.import = ["~/.config/alacritty/nord.toml"]

[window]
opacity = 0.7

[colors]
transparent_background_colors = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen"}]

[terminal]
osc52 = "CopyPaste"
